### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by jpjarnoux**
Adding metadata to pangenome on all elements

### CODE REVIEW

**Comment by ggautreau** [comment]
In writeMetadata.py, is this chunk of code correct? (metasources["genes"] assigned to RGPs, spots and modules ?) 
```
if metastatus["RGPs"] in ["Computed", "Loaded", "inFile"]:
        metadata_group._v_attrs.RGPs = True
        metasources_group._v_attrs.RGPs = metasources["genes"]
    if metastatus["spots"] in ["Computed", "Loaded", "inFile"]:
        metadata_group._v_attrs.spots = True
        metasources_group._v_attrs.spots = metasources["genes"]
    if metastatus["modules"] in ["Computed", "Loaded", "inFile"]:
        metadata_group._v_attrs.modules = True
        metasources_group._v_attrs.modules = metasources["genes"]
```
also this line of code is executed even for RGPs, spots, and modules, is it correct? (line 242, 250, 258)
```
 logging.getLogger().info("Writing **genes** metadata in pangenome")
```

**Comment by ggautreau** [comment]
some typos in metadata help :
```Allow to pass if a key in metadata is not find in pangenome (default: False)``` ==> ```Allow to pass if a key in metadata is not found in pangenome (default: False)``` 
```See our github for more detail about format``` ==> ```See our GitHub documentation for more details about format```

**Comment by ggautreau** [comment]
> Hi @jpjarnoux, In writeMetadata.py, is this chunk of code correct? (metasources["genes"] assigned to RGPs, spots and modules ?)
> 
> ```
> if metastatus["RGPs"] in ["Computed", "Loaded", "inFile"]:
>         metadata_group._v_attrs.RGPs = True
>         metasources_group._v_attrs.RGPs = metasources["genes"]
>     if metastatus["spots"] in ["Computed", "Loaded", "inFile"]:
>         metadata_group._v_attrs.spots = True
>         metasources_group._v_attrs.spots = metasources["genes"]
>     if metastatus["modules"] in ["Computed", "Loaded", "inFile"]:
>         metadata_group._v_attrs.modules = True
>         metasources_group._v_attrs.modules = metasources["genes"]
> ```

Thank you very much @JeanMainguy for fixing this part 😃 .

I have another doubt about line 111 of the main.yml file, the flag --omit is added to the command because the metadata file ( testingDataset/metadata/metadata_families.tsv ) can fit a new pangenome. I think a fake metadata file fitting the true pangenome should be generated to avoid invisible bugs due to the flat --omit. What do you think about this @jpjarnoux ?

Anyway, I had trouble with the metadata command to associate information to spot. I just generated the C. trachomatis pangenome and I tried to import this simple metadata file `spots.tsv` :
```
spots   rgp_test_id
spot_0  NC_022117.1_RGP_0
spot_1  NC_021892.1_RGP_0
```

using this command : 
```
ppanggolin metadata -p testingDataset/ppanggolin_output_DATE2023-04-28_HOUR17.45.26_PID30616/pangenome.h5 -m testingDataset/ppanggolin_output_DATE2023-04-28_HOUR17.45.26_PID30616/spots.tsv -a spots -s test4
```

and I got the following issues : 
```
Exception: Unexpected attribute. A recent change could create this error. Please report the error on our github.
```

Is there a bug @jpjarnoux @JeanMainguy ?

Thx.

**Comment by JeanMainguy** [comment]
Hello, 
Yes There is still some trouble associating metadata to spot and module. 
@jpjarnoux  is going to look at it...

**Pull request merged**
