### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by sletort**
Here are a first set of tests for genome.py file.
I used pytest with :
`PYTHONPATH=. pytest-3 -sv` from ppanggolin dir.
-> I set PYTHONPATH because I cannot make pytest load module genome otherwise. I suppose my installation of Ppanggolin is not well done.

Note: I didn't provide a test for Gene because I think a factorization with RNA can be done, next PR will come.

Tell me whatever have to be changed before I provide more tests.

Note2: shouldn't the method Organism.addContig be named Organism.getContig ?

### CODE REVIEW

**Comment by sletort** [comment]
In my latest commit I corrected the import of libraries.
`from genome` -> `from ppanggolin.genome`  
Now it can be ran from the top of the repo.

**Comment by axbazin** [comment]
Sorry for not responding quickly, I'm not in the lab and have a poor internet access atm.
Indeed getContig seems like a more appropriate name as it is what it does most of the time.

I merged your two other PRs they were good suggestions. If I'm not mistaken, pytest should work without setting the PYTHONPATH with your latest commit right ?

**Comment by axbazin** [comment]
I got confused. So addContig has the tare to have two behaviors. if the contig does exist it returns it, and if it does not it adds it to the Organism and returns it. So in any case neither getContig nor addContig are ideal names I guess?

**Comment by sletort** [comment]
yes, to run tests, the minimal command is now pytest-3.

Considering addContig method, I think getContig is a good name, even if the contig comes from a new creation. Here is my reflexion : as a user, I don't care how I got the contig. I ask the organism object to give me a contig he owns, and after the call I received a contig, and the organism owns it.

I have to admit that in django framework for example they have a get_or_create function.
So it's up to you :)

**Comment by axbazin** [comment]
The explicit naming of both actions was chosen.
Is this PR good to be merged, or are you planning to add other tests to it ?

**Comment by sletort** [comment]
I'll resync the branch and add a test for Gene.

**Comment by sletort** [comment]
This time I'm done with this PR. :)

**Pull request merged**
